#!/bin/bash

for i in $*; do echo $i; find $i -name "rplraw.mat" | wc -l; find $i -name "runosort*" | xargs grep -L Error | wc -l; done

# for i in $*; do echo $i; find $i -name "rplraw.mat" | wc -l; find $i -name "P1*mat" | wc -l; done

